INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','HOSPITAL','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','HOSPITAL','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','HOME','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','HOME','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','HUNGRY','AGE_TYPE',1,''),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','HUNGRY','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','2_HOURS','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','2_HOURS','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','HBA1C','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','HBA1C','AGE_TYPE',2,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','SGOT','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','SGOT','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','SGPT','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','SGPT','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','CHOL','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','CHOL','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','LDL','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','LDL','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','HDL','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','HDL','AGE_TYPE',2,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','TRI','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','TRI','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','URE','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','URE','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','CREA','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','CREA','AGE_TYPE',2,NULL),
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','AXIT_URIC','AGE_TYPE',1,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','AXIT_URIC','AGE_TYPE',2,NULL),
	 ('Trên 5 đến < 12 tuổi','FROM_5_LESS_THAN_12','BMI','AGE_TYPE',1,NULL),
	 ('Từ 12 đến 19 tuổi','FROM_12_LESS_THAN_20','BMI','AGE_TYPE',2,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Trên 19 tuổi đến < 70 tuổi','FROM_20_LESS_THAN_70','BMI','AGE_TYPE',3,NULL),
	 ('>= 70 tuổi','EQUAL_MORE_THAN_70','BMI','AGE_TYPE',4,NULL),
	 ('Từ 0 tuổi đến < 2 tuổi','FROM_0_LESS_THAN_2','WEIGHT_HEIGHT','AGE_TYPE',1,NULL),
	 ('Từ 2 đến < 5 tuổi','FROM_2_LESS_THAN_5','WEIGHT_HEIGHT','AGE_TYPE',2,NULL),
	 ('Khoảng','ABOUT','HOSPITAL','INDICATOR',1,NULL),
	 ('>','MORE_THAN','HOSPITAL','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','HOSPITAL','INDICATOR',3,NULL),
	 ('<','LESS_THAN','HOSPITAL','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','HOSPITAL','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','HOME','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','HOME','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','HOME','INDICATOR',3,NULL),
	 ('<','LESS_THAN','HOME','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','HOME','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','HUNGRY','INDICATOR',1,NULL),
	 ('>','MORE_THAN','HUNGRY','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','HUNGRY','INDICATOR',3,NULL),
	 ('<','LESS_THAN','HUNGRY','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','HUNGRY','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','2_HOURS','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','2_HOURS','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','2_HOURS','INDICATOR',3,NULL),
	 ('<','LESS_THAN','2_HOURS','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','2_HOURS','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','HBA1C','INDICATOR',1,NULL),
	 ('>','MORE_THAN','HBA1C','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','HBA1C','INDICATOR',3,NULL),
	 ('<','LESS_THAN','HBA1C','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','HBA1C','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','SGOT','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','SGOT','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','SGOT','INDICATOR',3,NULL),
	 ('<','LESS_THAN','SGOT','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','SGOT','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','SGPT','INDICATOR',1,NULL),
	 ('>','MORE_THAN','SGPT','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','SGPT','INDICATOR',3,NULL),
	 ('<','LESS_THAN','SGPT','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','SGPT','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','CHOL','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','CHOL','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','CHOL','INDICATOR',3,NULL),
	 ('<','LESS_THAN','CHOL','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','CHOL','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','LDL','INDICATOR',1,NULL),
	 ('>','MORE_THAN','LDL','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','LDL','INDICATOR',3,NULL),
	 ('<','LESS_THAN','LDL','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','LDL','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','HDL','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','HDL','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','HDL','INDICATOR',3,NULL),
	 ('<','LESS_THAN','HDL','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','HDL','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','TRI','INDICATOR',1,NULL),
	 ('>','MORE_THAN','TRI','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','TRI','INDICATOR',3,NULL),
	 ('<','LESS_THAN','TRI','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','TRI','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','URE','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','URE','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','URE','INDICATOR',3,NULL),
	 ('<','LESS_THAN','URE','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','URE','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','CREA','INDICATOR',1,NULL),
	 ('>','MORE_THAN','CREA','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','CREA','INDICATOR',3,NULL),
	 ('<','LESS_THAN','CREA','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','CREA','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','AXIT_URIC','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','AXIT_URIC','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','AXIT_URIC','INDICATOR',3,NULL),
	 ('<','LESS_THAN','AXIT_URIC','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','AXIT_URIC','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','BMI','INDICATOR',1,NULL),
	 ('>','MORE_THAN','BMI','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','BMI','INDICATOR',3,NULL),
	 ('<','LESS_THAN','BMI','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','BMI','INDICATOR',5,NULL),
	 ('Khoảng','ABOUT','WEIGHT_HEIGHT','INDICATOR',1,NULL);
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('>','MORE_THAN','WEIGHT_HEIGHT','INDICATOR',2,NULL),
	 ('>=','MORE_THAN_OR_EQUAL','WEIGHT_HEIGHT','INDICATOR',3,NULL),
	 ('<','LESS_THAN','WEIGHT_HEIGHT','INDICATOR',4,NULL),
	 ('<=','LESS_THAN_OR_EQUAL','WEIGHT_HEIGHT','INDICATOR',5,NULL),
	 ('Huyết áp tối ưu','BLOOD_PRESSURE_MAX','HOSPITAL','TYPE',1,'#4F71BE'),
	 ('Tăng huyết áp độ 1','BLOOD_PRESSURE_ONE','HOSPITAL','TYPE',4,'#FD9602'),
	 ('Tăng huyết áp độ 2','BLOOD_PRESSURE_TWO','HOSPITAL','TYPE',5,'#B02418'),
	 ('Tăng huyết áp độ 3','BLOOD_PRESSURE_THREE','HOSPITAL','TYPE',6,'#EA3323'),
	 ('Huyết áp bình thường','BLOOD_PRESSURE_NORMAL','HOSPITAL','TYPE',2,'#4FAD5B'),
	 ('Huyết áp tâm thu đơn độc','ISOLATED_SYSTOLIC_HYPERTENSION','HOSPITAL','TYPE',7,'#A5A5A5');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Tiền tăng huyết áp','PREHYPERTENSION','HOSPITAL','TYPE',3,'#F5C242'),
	 ('Tăng huyết áp','BLOOD_PRESSURE','HOME','TYPE',1,'#DE8344'),
	 ('Không được phân loại vào nhóm Tăng huyết áp','BLOOD_PRESSURE_NONE','HOME','TYPE',2,'#4FAD5B'),
	 ('Đái tháo đường','DIABETES','HUNGRY','TYPE',1,'#F5540A'),
	 ('Tiền đái tháo đường','PRE_DIABETES','HUNGRY','TYPE',2,'#FD9602'),
	 ('Bình thường','NORMAL','HUNGRY','TYPE',3,'#4CCA35'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','HUNGRY','TYPE',4,'#1AA8E3'),
	 ('Đái tháo đường','DIABETES','2_HOURS','TYPE',1,'#F5540A'),
	 ('Tiền đái tháo đường','PRE_DIABETES','2_HOURS','TYPE',2,'#FD9602'),
	 ('Không thuộc Tiền Đái tháo đường hay Đái tháo đường','NORMAL','2_HOURS','TYPE',3,'#4CCA35');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Đái tháo đường','DIABETES','HBA1C','TYPE',1,'#F5540A'),
	 ('Tiền đái tháo đường','PRE_DIABETES','HBA1C','TYPE',2,'#FD9602'),
	 ('Không thuộc Tiền Đái tháo đường/ Đái tháo đường','NORMAL','HBA1C','TYPE',3,'#4CCA35'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','HBA1C','TYPE',4,'#1AA8E3'),
	 ('Bình thường','NORMAL','SGOT','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','SGOT','TYPE',2,'#FD9602'),
	 ('Bình thường','NORMAL','SGPT','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','SGPT','TYPE',2,'#FD9602'),
	 ('Bình thường','NORMAL','CHOL','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','CHOL','TYPE',2,'#FD9602');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','CHOL','TYPE',3,'#1AA8E3'),
	 ('Bình thường','NORMAL','LDL','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','LDL','TYPE',2,'#FD9602'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','LDL','TYPE',3,'#1AA8E3'),
	 ('Bình thường','NORMAL','HDL','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','HDL','TYPE',2,'#FD9602'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','HDL','TYPE',3,'#1AA8E3'),
	 ('Bình thường','NORMAL','TRI','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','TRI','TYPE',2,'#FD9602'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','TRI','TYPE',3,'#FD9602');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Bình thường','NORMAL','URE','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','URE','TYPE',2,'#FD9602'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','URE','TYPE',3,'#1AA8E3'),
	 ('Bình thường','NORMAL','CREA','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','CREA','TYPE',2,'#FD9602'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','CREA','TYPE',3,'#1AA8E3'),
	 ('Bình thường','NORMAL','AXIT_URIC','TYPE',1,'#4CCA35'),
	 ('Cao hơn mức bình thường','MORE_THAN_NORMAL','AXIT_URIC','TYPE',2,'#FD9602'),
	 ('Thấp hơn mức bình thường','LESS_THAN_NORMAL','AXIT_URIC','TYPE',3,'#1AA8E3'),
	 ('Bé bị Suy dinh dưỡng thấp còi, mức độ nặng.','LESS_3SD','HEIGHT','TYPE',1,'#A4DDF5CC');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Bé bị Suy dinh dưỡng thấp còi.','FROM_3SD_LESS_THAN_3SD','HEIGHT','TYPE',2,'#FECF8BCC'),
	 ('Bé phát triển Chiều cao/chiều dài bình thường.','FROM_2SD_LESS_THAN_2SD','HEIGHT','TYPE',3,'#99E18CCC'),
	 ('Bé phát triển Chiều cao/chiều dài cao hơn so với chuẩn.','FROM_2SD_LESS_THAN_3SD','HEIGHT','TYPE',4,'#FAA781CC'),
	 ('Bé phát triển Chiều cao/chiều dài rất cao, cao hơn so với chuẩn, cần cho trẻ đi khám để kiểm tra về rối loạn nội tiết.','MORE_THAN_3SD','HEIGHT','TYPE',5,'#EB5447CC'),
	 ('Suy dinh dưỡng nhẹ cân, mức độ nặng','LESS_3SD','WEIGHT','TYPE',1,'#A4DDF5CC'),
	 ('Suy dinh dưỡng nhẹ cân, mức độ vừa','FROM_3SD_LESS_THAN_3SD','WEIGHT','TYPE',2,'#FECF8BCC'),
	 ('Bình thường','FROM_2SD_LESS_THAN_2SD','WEIGHT','TYPE',3,'#99E18CCC'),
	 ('Có nguy cơ thừa cân','FROM_2SD_LESS_THAN_3SD','WEIGHT','TYPE',4,'#FAA781CC'),
	 ('Có nguy cơ thừa cân','MORE_THAN_3SD','WEIGHT','TYPE',5,'#EB5447CC'),
	 ('Suy dinh dưỡng gầy còm, mức độ nặng','LESS_3SD','WEIGHT_HEIGHT','TYPE',1,'#00A9F0CC');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Suy dinh dưỡng gầy còm, mức độ vừa','FROM_3SD_LESS_THAN_3SD','WEIGHT_HEIGHT','TYPE',2,'#33C3FFCC'),
	 ('Bình thường','FROM_2SD_LESS_THAN_2SD','WEIGHT_HEIGHT','TYPE',3,'#99E18CCC'),
	 ('Thừa cân','FROM_2SD_LESS_THAN_3SD','WEIGHT_HEIGHT','TYPE',4,'#FAA781CC'),
	 ('Béo phì','MORE_THAN_3SD','WEIGHT_HEIGHT','TYPE',5,'#EB5447CC'),
	 ('Suy dinh dưỡng gầy còm, mức độ nặng','LESS_THAN_3SD','BMI','TYPE',1,'#1AA8E3'),
	 ('Suy dinh dưỡng gầy còm, mức độ vừa','FROM_3SD_LESS_THAN_2SD','BMI','TYPE',2,'#FD9602'),
	 ('Bình thường','FROM_2SD_LESS_THAN_2SD','BMI','TYPE',3,'#FD9602'),
	 ('Thừa cân','FROM_2SD_LESS_THAN_3SD','BMI','TYPE',4,'#F5540A'),
	 ('Béo phì','MORE_THAN_3SD','BMI','TYPE',5,'#1AA8E3'),
	 ('Gầy độ 3','UNDERWEGHT_THREE','BMI','TYPE_1',1,'#00A9F0CC');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Gầy độ 2','UNDERWEGHT_TWO','BMI','TYPE_1',2,'#00ADF5'),
	 ('Gầy độ 1','UNDERWEGHT_ONE','BMI','TYPE_1',3,'#A4DDF5CC'),
	 ('Bình thường','NORMAL','BMI','TYPE_1',4,'#99E18CCC'),
	 ('Tiền béo phì','OBESITY_PRE','BMI','TYPE_1',5,'#FFE666CC'),
	 ('Béo phì độ I','OBESITY_ONE','BMI','TYPE_1',6,'#FECF8BCC'),
	 ('Béo phì độ II','OBESITY_TWO','BMI','TYPE_1',7,'#FAA781CC'),
	 ('Béo phì độ III','OBESITY_THREE','BMI','TYPE_1',8,'#EB5447CC'),
	 ('Suy dinh dưỡng gầy còm, mức độ nặng','LESS_THAN_3SD','BMI_5_19','TYPE',1,'#1AA8E3'),
	 ('Suy dinh dưỡng gầy còm, mức độ vừa','FROM_3SD_LESS_THAN_2SD','BMI_5_19','TYPE',2,'#FD9602'),
	 ('Bình thường','FROM_2SD_LESS_THAN_1SD','BMI_5_19','TYPE',3,'#4CCA35');
INSERT INTO conclusion_recommend_dropbox (NAME,CODE,MODEL,`TYPE`,`INDEX`,COLOR) VALUES
	 ('Thừa cân','FROM_1SD_LESS_THAN_2SD','BMI_5_19','TYPE',4,'#F5540A'),
	 ('Béo phì','MORE_THAN_2SD','BMI_5_19','TYPE',5,'#E52A1A');
