INSERT INTO tips (TIP) VALUES
('Hãy duy trì thói quen uống đủ nước mỗi ngày, khoảng 2 lít, vì nước không chỉ giúp cơ thể loại bỏ độc tố mà còn giữ cho làn da tươi trẻ, tinh thần tỉnh táo và các cơ quan hoạt động nhịp nhàng.'),
('Bữa sáng lành mạnh sẽ cung cấp cho bạn nguồn năng lượng cần thiết để bắt đầu ngày mới hiệu quả; hãy chọn những thực phẩm giàu protein và chất xơ thay vì đồ ngọt để cơ thể no lâu và khỏe mạnh.'),
('Một giấc ngủ sâu từ 7 đến 8 tiếng mỗi đêm giúp não bộ nghỉ ngơi, phục hồi trí nhớ và tái tạo năng lượng cho cơ thể, từ đó tăng cường hiệu suất làm việc vào ngày hôm sau.'),
('Dành ít nhất 30 phút mỗi ngày để đi bộ hoặc vận động nhẹ, không chỉ giúp lưu thông máu tốt hơn mà còn làm tinh thần bạn thư thái và giảm nguy cơ mắc các bệnh tim mạch.'),
('Rau xanh và trái cây là nguồn vitamin và khoáng chất tự nhiên vô giá; bổ sung chúng mỗi ngày sẽ giúp hệ miễn dịch khỏe mạnh, làn da sáng mịn và hệ tiêu hóa hoạt động trơn tru.'),
('Thói quen tiêu thụ quá nhiều thức ăn nhanh có thể gây ra thừa cân và các bệnh về tim mạch; hãy tự chăm sóc mình bằng cách ưu tiên những bữa ăn nấu tại nhà, cân bằng giữa rau, đạm và tinh bột.'),
('Một buổi tập thể dục vào buổi sáng sẽ giúp bạn khởi động cơ thể, làm tăng nhịp tim, cải thiện sự tập trung và mang đến nguồn năng lượng tích cực để bắt đầu ngày mới.'),
('Uống một ly nước ấm ngay sau khi thức dậy sẽ đánh thức hệ tiêu hóa, hỗ trợ thải độc tố ra khỏi cơ thể và giúp bạn cảm thấy sảng khoái hơn để khởi đầu ngày mới.'),
('Một nụ cười không chỉ làm tâm trạng bạn vui vẻ mà còn giúp giảm căng thẳng, cải thiện hệ miễn dịch và tạo sự kết nối tích cực với những người xung quanh.'),
('Việc ngồi quá lâu mà không vận động có thể gây hại cho cột sống và tuần hoàn máu; hãy đứng dậy đi lại hoặc vươn vai sau mỗi giờ làm việc để cơ thể luôn linh hoạt và khỏe mạnh.'),
('Hạn chế thức khuya vì việc ngủ muộn thường xuyên sẽ khiến cơ thể mệt mỏi, giảm khả năng tập trung và làm suy yếu hệ miễn dịch.'),
('Hãy dành thời gian hít thở sâu mỗi ngày để giảm căng thẳng, cải thiện tâm trạng và tăng cường lượng oxy cho não.'),
('Đừng quên giãn cơ nhẹ nhàng sau khi làm việc hoặc tập luyện để tránh căng cơ và giúp cơ thể phục hồi nhanh hơn.'),
('Ăn chậm, nhai kỹ giúp hệ tiêu hóa hoạt động hiệu quả hơn và giúp bạn cảm nhận rõ hương vị món ăn.'),
('Giữ không gian sống và làm việc gọn gàng, sạch sẽ sẽ giúp tinh thần bạn thoải mái và tăng khả năng tập trung.'),
('Hạn chế sử dụng điện thoại hoặc máy tính trước khi đi ngủ để tránh ánh sáng xanh gây rối loạn giấc ngủ.'),
('Hãy bắt đầu ngày mới bằng một vài phút thiền hoặc hít thở sâu để tâm trí tĩnh lặng và chuẩn bị tinh thần tích cực.'),
('Tạo thói quen kiểm tra sức khỏe định kỳ giúp bạn phát hiện sớm các vấn đề và bảo vệ bản thân tốt hơn.'),
('Bổ sung đủ protein trong mỗi bữa ăn giúp xây dựng cơ bắp, duy trì năng lượng và hỗ trợ quá trình trao đổi chất.'),
('Hãy lắng nghe cơ thể mình – khi mệt, hãy nghỉ ngơi; khi đói, hãy ăn uống lành mạnh thay vì cố gắng chịu đựng.'),
('Tránh bỏ bữa, đặc biệt là bữa sáng, vì nó giúp cân bằng đường huyết và duy trì năng lượng suốt ngày dài.'),
('Hãy dành thời gian mỗi ngày để thư giãn hoặc làm điều bạn yêu thích, giúp giảm stress và cải thiện sức khỏe tinh thần.'),
('Hạn chế đồ uống có cồn, vì chúng làm giảm chất lượng giấc ngủ và gây mất cân bằng dinh dưỡng trong cơ thể.'),
('Ăn uống đúng giờ giúp hệ tiêu hóa làm việc hiệu quả và ổn định nhịp sinh học của cơ thể.'),
('Nghe nhạc nhẹ nhàng có thể giúp giảm huyết áp, cải thiện tâm trạng và mang lại cảm giác thư giãn sâu.'),
('Giữ tư thế ngồi đúng khi làm việc với máy tính để tránh đau lưng, mỏi cổ và các vấn đề về cột sống.'),
('Thường xuyên rửa tay sạch sẽ giúp phòng tránh lây nhiễm vi khuẩn và bảo vệ sức khỏe cho bản thân và gia đình.'),
('Hãy đặt mục tiêu nhỏ mỗi ngày như uống đủ nước, đi bộ 15 phút hay ngủ sớm hơn – dần dần chúng sẽ trở thành thói quen tốt.'),
('Bổ sung các loại hạt như hạnh nhân, óc chó hoặc hạt chia vào khẩu phần ăn để cung cấp chất béo tốt và năng lượng cho cơ thể.'),
('Luôn biết ơn và duy trì thái độ tích cực – điều này không chỉ làm tinh thần lạc quan mà còn có lợi cho sức khỏe tim mạch.');
