-- Create chat_conversations table
CREATE TABLE IF NOT EXISTS `chat_conversations` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CONVERSATION_ID` varchar(255) NOT NULL,
  `USER_ID` int NOT NULL,
  `IS_ACTIVE` tinyint NOT NULL DEFAULT '1',
  `CREATED_AT` bigint NOT NULL,
  `EXPIRES_AT` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_CONVERSATION_ID` (`CONVERSATION_ID`),
  KEY `IDX_USER_ID` (`USER_ID`),
  KEY `IDX_ACTIVE_USER` (`USER_ID`, `IS_ACTIVE`),
  CONSTRAINT `FK_CONVERSATION_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create chat_messages table
CREATE TABLE IF NOT EXISTS `chat_messages` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CONVERSATION_ID` varchar(255) NOT NULL,
  `ROLE` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `INTENT` varchar(50) DEFAULT NULL,
  `MODE` varchar(50) DEFAULT NULL,
  `CREATED_AT` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_MESSAGE_CONVERSATION` (`CONVERSATION_ID`),
  KEY `IDX_MESSAGE_CREATED_AT` (`CONVERSATION_ID`, `CREATED_AT`),
  CONSTRAINT `FK_MESSAGE_CONVERSATION` FOREIGN KEY (`CONVERSATION_ID`) REFERENCES `chat_conversations` (`CONVERSATION_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
